; File autogenerated by build-queries-nvim.py; do not edit

(recipe 
  (recipe_body) .inner) .outer

(parameters 
  ((_) .inner . ","? .outer)) .outer

(dependency_expression
  (_) .inner) .outer

(function_call
  arguments: (sequence (expression) .inner) .outer) .outer

(comment) .outer
