; File autogenerated by build-queries-nvim.py; do not edit

; Specify how to navigate around logical blocks in code

(recipe
  (recipe_body) @function.inner) @function.outer

(parameters
  ((_) @parameter.inner . ","? @parameter.outer)) @parameter.outer

(dependency_expression
  (_) @parameter.inner) @parameter.outer

(function_call
  arguments: (sequence
    (expression) @parameter.inner) @parameter.outer) @function.outer

(comment) @comment.outer
