#!/usr/bin/env python3
"""Generate NeoVim queries.

Everything in `queries/` uses tree-sitter syntax, as defined at
<https://tree-sitter.github.io/tree-sitter/syntax-highlighting#theme>. However, NVim
has a slightly different syntax.

This file performs conversions so two sets of files don't need to be maintained.

<https://docs.helix-editor.com/master/themes.html#syntax-highlighting> has a bit better
guide for these parameters than tree-sitter does.
    
"""

from glob import glob

REPLACEMENTS = [
    ("@local.definition", "@definition"),
    ("@local.reference", "@reference"),
    ("@local.scope", "@scope"),
    ("@constants.builtin.boolean", "@boolean"),
    ("@keyword.control.conditional", "@conditional"),
    ("@variable.parameter", "@parameter"),
    ("@comment.line", "@comment"),
    ("@constant.character.escape", "@string.escape"),
]

def main():
    sources = glob("queries/*.scm")
    for fname in sources:
        contents = "; File autogenerated by build-queries-nvim.py; do not edit\n\n"
        
        with open(fname) as f:
            contents += f.read()
            
        for (x, to) in REPLACEMENTS:
            contents = contents.replace(x, to)

        print(contents)
    

if __name__ == "__main__":
    main()
