; File autogenerated by build-queries-nvim.py; do not edit

; This query specifies how to auto-indent logical blocks.
;

[
  (recipe)
  (string)
  (external_command)
] @indent.begin

(comment) @indent.auto
