; File autogenerated by build-queries-nvim.py; do not edit

; This query 
;
; Better documentation is in https://docs.helix-editor.com/guides/indent.html

(recipe) @indent @extend
(string_literal) @indent @extend
(external_command) @indent @extend
