; File autogenerated by build-queries-nvim.py; do not edit

(comment) @comment

; FIXME: shebang
; (shebang_recipe 
;     (shebang 
;         interpreter:(TEXT) @language)
;     (shebang_body) @content
; ) 

(source_file 
    ; (item (setting lang:(identifier) @language))
    (recipe (recipe_body) @content)
) 

; (interpolation (expression) @just)
