; File autogenerated by build-queries-nvim.py; do not edit

; This query specifies how nested languages are handled

((comment) @injection.content
  (#set! injection.language "comment"))



(recipe_line
    (text) @injection.content
    (#set! injection.language "bash"))

 (recipe_body
     (shebang) @injection.shebang 
     (recipe_line
         (text) @injection.content
         (#set! injection.language "python")))

(external_command
    (command_body) @injection.content
    (#set! injection.language "bash"))

((regex_literal
    [
        (string_literal)
        (raw_string_literal)
    ] @injection.content)
    (#set! injection.language "regex"))
