; File autogenerated by build-queries-nvim.py; do not edit

; This file tells us about the scope of variables so e.g. local
; variables override global functions with the same name

; Scope

(recipe) @scope

; Definitions

(alias
  left: (identifier) @definition.var)

(assignment
  left: (identifier) @definition.var)

(module
  name: (identifier) @definition.namespace)

(parameter
  name: (identifier) @definition.var)

(recipe_header
  name: (identifier) @definition.function)

; References

(alias
  right: (identifier) @reference)

(function_call
  name: (identifier) @reference)

(dependency
  name: (identifier) @reference)

(dependency_expression
  name: (identifier) @reference)

(value
  (identifier) @reference)
