; File autogenerated by build-queries-nvim.py; do not edit

; This file tells us about the scope of variables so e.g. local
; variables override global functions with the same name

(recipe) @scope

; definition sources
(alias left: (identifier) @definition.variable)
(assignment left: (identifier) @definition.variable)
(module mod_name: (identifier) @definition.namespace)
(parameter param: (identifier) @definition.variable)
(recipe_header recipe_name: (identifier) @definition.function)

; reference locations
(alias right: (identifier) @reference.variable)
(function_call name: (identifier) @reference.function)
(dependency recipe: (identifier) @reference.function)
(dependency_expression recipe: (identifier) @reference.function)
(value (identifier) @reference.variable)
