; File autogenerated by build-queries-nvim.py; do not edit

(recipe 
  (recipe_body) @function.inside) @function.around

(parameters 
  ((_) @parameter.inside . ","? @parameter.around)) @parameter.around

(dependency_expression
  (_) @parameter.inside) @parameter.around

(function_call
  arguments: (sequence (expression) @parameter.inside) @parameter.around) @function.around

(comment) @comment.around
